//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrmAssistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrmAssistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutOptions_EditorTitle_About {
            get {
                return ResourceManager.GetString("AboutOptions_EditorTitle_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❤️Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralOptions_EditorTitle_General_Options {
            get {
                return ResourceManager.GetString("GeneralOptions_EditorTitle_General_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto merge multiple versions stored in the same folder. Default is OFF..
        /// </summary>
        public static string GeneralOptions_MergeMultiVersion_Auto_merge_multiple_versions_if_in_the_same_folder_ {
            get {
                return ResourceManager.GetString("GeneralOptions_MergeMultiVersion_Auto_merge_multiple_versions_if_in_the_same_fold" +
                        "er_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Merge Multi-version.
        /// </summary>
        public static string GeneralOptions_MergeMultiVersion_Merge_Multiple_Versions {
            get {
                return ResourceManager.GetString("GeneralOptions_MergeMultiVersion_Merge_Multiple_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Scope.
        /// </summary>
        public static string IntroSkipOptions_LibraryScope_Library_Scope {
            get {
                return ResourceManager.GetString("IntroSkipOptions_LibraryScope_Library_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV shows library scope to detect. Blank includes all TV shows libraries..
        /// </summary>
        public static string IntroSkipOptions_LibraryScope_TV_shows_library_scope_to_detect__Blank_includes_all_ {
            get {
                return ResourceManager.GetString("IntroSkipOptions_LibraryScope_TV_shows_library_scope_to_detect__Blank_includes_al" +
                        "l_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Credits Duration (Seconds).
        /// </summary>
        public static string IntroSkipOptions_MaxCreditsDurationSeconds {
            get {
                return ResourceManager.GetString("IntroSkipOptions_MaxCreditsDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Intro Duration (Seconds).
        /// </summary>
        public static string IntroSkipOptions_MaxIntroDurationSeconds {
            get {
                return ResourceManager.GetString("IntroSkipOptions_MaxIntroDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Users.
        /// </summary>
        public static string IntroSkipOptions_UserScope_User_Scope {
            get {
                return ResourceManager.GetString("IntroSkipOptions_UserScope_User_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users allowed to detect. Blank includes all users..
        /// </summary>
        public static string IntroSkipOptions_UserScope_Users_allowed_to_detect__Blank_includes_all {
            get {
                return ResourceManager.GetString("IntroSkipOptions_UserScope_Users_allowed_to_detect__Blank_includes_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize MovieDb Fallback Language.
        /// </summary>
        public static string ModOptions_ChineseMovieDb_Chinese_MovieDb {
            get {
                return ResourceManager.GetString("ModOptions_ChineseMovieDb_Chinese_MovieDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to get Chinese or Japanese metadata from MovieDb. Default is OFF..
        /// </summary>
        public static string ModOptions_ChineseMovieDb_Optimize_MovieDb_for_Chinese_metadata__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_ChineseMovieDb_Optimize_MovieDb_for_Chinese_metadata__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive MediaInfo Extract.
        /// </summary>
        public static string ModOptions_ExclusiveExtract_Exclusive_Extract {
            get {
                return ResourceManager.GetString("ModOptions_ExclusiveExtract_Exclusive_Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only allow this plugin to extract media info (ffprobe) and capture image (ffmpeg). Default is OFF..
        /// </summary>
        public static string ModOptions_ExclusiveExtract_Only_allow_this_plugin_to_extract_media_info__ffprobe__and_capture_image__ffmpeg___Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_ExclusiveExtract_Only_allow_this_plugin_to_extract_media_info__ffprobe" +
                        "__and_capture_image__ffmpeg___Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback Languages.
        /// </summary>
        public static string ModOptions_FallbackLanguages_Fallback_Languages {
            get {
                return ResourceManager.GetString("ModOptions_FallbackLanguages_Fallback_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback metadata languages..
        /// </summary>
        public static string ModOptions_FallbackLanguages_Fallback_languages__Default_is_zh_SG_ {
            get {
                return ResourceManager.GetString("ModOptions_FallbackLanguages_Fallback_languages__Default_is_zh_SG_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Language Poster.
        /// </summary>
        public static string ModOptions_OriginalPoster_Original_Poster {
            get {
                return ResourceManager.GetString("ModOptions_OriginalPoster_Original_Poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show original poster based on original language. Default is OFF..
        /// </summary>
        public static string ModOptions_OriginalPoster_Show_original_poster_based_on_original_language__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_OriginalPoster_Show_original_poster_based_on_original_language__Defaul" +
                        "t_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch-up mode update - {0}\n\n{1}&apos;s favorite.
        /// </summary>
        public static string Notification_CatchupUpdate_EventDescription {
            get {
                return ResourceManager.GetString("Notification_CatchupUpdate_EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites Updated.
        /// </summary>
        public static string Notification_CatchupUpdate_EventName {
            get {
                return ResourceManager.GetString("Notification_CatchupUpdate_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} - Credits marker updated\n\nCredits duration: {2}\n\nby {3}.
        /// </summary>
        public static string Notification_CreditsUpdate_Description {
            get {
                return ResourceManager.GetString("Notification_CreditsUpdate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} - Credits marker updated.
        /// </summary>
        public static string Notification_CreditsUpdate_Message {
            get {
                return ResourceManager.GetString("Notification_CreditsUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntroSkip Updated.
        /// </summary>
        public static string Notification_IntroSkipUpdate_EventName {
            get {
                return ResourceManager.GetString("Notification_IntroSkipUpdate_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} - Intro marker updated\n\nIntro start time: {2}\nIntro end time: {3}\n\nby {4}.
        /// </summary>
        public static string Notification_IntroUpdate_Description {
            get {
                return ResourceManager.GetString("Notification_IntroUpdate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} - Intro marker updated.
        /// </summary>
        public static string Notification_IntroUpdate_Message {
            get {
                return ResourceManager.GetString("Notification_IntroUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch-up Mode.
        /// </summary>
        public static string PluginOptions_CatchupMode_Catch_up_Mode__Experimental_ {
            get {
                return ResourceManager.GetString("PluginOptions_CatchupMode_Catch_up_Mode__Experimental_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract media info for newly added items and sync intro and credits markers. Default is OFF..
        /// </summary>
        public static string PluginOptions_CatchupMode_Catch_up_users_favorites__exclusive_to_Strm___Default_is_False_ {
            get {
                return ResourceManager.GetString("PluginOptions_CatchupMode_Catch_up_users_favorites__exclusive_to_Strm___Default_i" +
                        "s_False_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strm Assistant.
        /// </summary>
        public static string PluginOptions_EditorTitle_Strm_Assistant {
            get {
                return ResourceManager.GetString("PluginOptions_EditorTitle_Strm_Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaInfo Extract.
        /// </summary>
        public static string PluginOptions_EditorTitle_Strm_Extract {
            get {
                return ResourceManager.GetString("PluginOptions_EditorTitle_Strm_Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Capture Enhanced.
        /// </summary>
        public static string PluginOptions_EnableImageCapture_Enable_Image_Capture {
            get {
                return ResourceManager.GetString("PluginOptions_EnableImageCapture_Enable_Image_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support image capture for Strm. Skip embedded image. Default is OFF..
        /// </summary>
        public static string PluginOptions_EnableImageCapture_Perform_image_capture_for_videos_without_primary_image__Default_is_False_ {
            get {
                return ResourceManager.GetString("PluginOptions_EnableImageCapture_Perform_image_capture_for_videos_without_primary" +
                        "_image__Default_is_False_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Intro Skip.
        /// </summary>
        public static string PluginOptions_EnableIntroSkip_Enable_Intro_Skip__Experimental_ {
            get {
                return ResourceManager.GetString("PluginOptions_EnableIntroSkip_Enable_Intro_Skip__Experimental_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback behavior-based intro and credits detection for episodes. Default is OFF..
        /// </summary>
        public static string PluginOptions_EnableIntroSkip_Enable_intro_skip_and_credits_skip_for_episodes__Default_is_False_ {
            get {
                return ResourceManager.GetString("PluginOptions_EnableIntroSkip_Enable_intro_skip_and_credits_skip_for_episodes__De" +
                        "fault_is_False_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Extra.
        /// </summary>
        public static string PluginOptions_IncludeExtra_Include_Extra {
            get {
                return ResourceManager.GetString("PluginOptions_IncludeExtra_Include_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include media extras to extract. Default is OFF..
        /// </summary>
        public static string PluginOptions_IncludeExtra_Include_media_extras_to_extract__Default_is_False_ {
            get {
                return ResourceManager.GetString("PluginOptions_IncludeExtra_Include_media_extras_to_extract__Default_is_False_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please uninstall the conflict plugin StrmExtract.dll and then restart Emby..
        /// </summary>
        public static string PluginOptions_IncompatibleMessage_Please_uninstall_the_conflict_plugin_Strm_Extract {
            get {
                return ResourceManager.GetString("PluginOptions_IncompatibleMessage_Please_uninstall_the_conflict_plugin_Strm_Extra" +
                        "ct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro and Credits Detection.
        /// </summary>
        public static string PluginOptions_IntroSkipOptions_Intro_Credits_Detection {
            get {
                return ResourceManager.GetString("PluginOptions_IntroSkipOptions_Intro_Credits_Detection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Scope.
        /// </summary>
        public static string PluginOptions_LibraryScope_Library_Scope {
            get {
                return ResourceManager.GetString("PluginOptions_LibraryScope_Library_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library scope to extract. Blank includes all..
        /// </summary>
        public static string PluginOptions_LibraryScope_Library_scope_to_extract__Blank_includes_all_ {
            get {
                return ResourceManager.GetString("PluginOptions_LibraryScope_Library_scope_to_extract__Blank_includes_all_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Concurrent Count.
        /// </summary>
        public static string PluginOptions_MaxConcurrentCount_Max_Concurrent_Count {
            get {
                return ResourceManager.GetString("PluginOptions_MaxConcurrentCount_Max_Concurrent_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max concurrent count of threads to extract media info. It must be between 1 to 10. Default is 1..
        /// </summary>
        public static string PluginOptions_MaxConcurrentCount_Max_Concurrent_Count_must_be_between_1_to_10__Default_is_1_ {
            get {
                return ResourceManager.GetString("PluginOptions_MaxConcurrentCount_Max_Concurrent_Count_must_be_between_1_to_10__De" +
                        "fault_is_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod.
        /// </summary>
        public static string PluginOptions_ModOptions_Mod_Features {
            get {
                return ResourceManager.GetString("PluginOptions_ModOptions_Mod_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Strm only. Turn off to also include Non-Strm. Default is ON..
        /// </summary>
        public static string PluginOptions_StrmOnly_Extract_media_info_of_Strm_only__Default_is_True_ {
            get {
                return ResourceManager.GetString("PluginOptions_StrmOnly_Extract_media_info_of_Strm_only__Default_is_True_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strm Only.
        /// </summary>
        public static string PluginOptions_StrmOnly_Strm_Only {
            get {
                return ResourceManager.GetString("PluginOptions_StrmOnly_Strm_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repo Link.
        /// </summary>
        public static string Repo_Link {
            get {
                return ResourceManager.GetString("Repo_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Link.
        /// </summary>
        public static string Wiki_Link {
            get {
                return ResourceManager.GetString("Wiki_Link", resourceCulture);
            }
        }
    }
}
