//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrmAssistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrmAssistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutOptions_EditorTitle_About {
            get {
                return ResourceManager.GetString("AboutOptions_EditorTitle_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears behavior-based intro and credits markers.
        /// </summary>
        public static string ClearChapterMarkersTask_Description_Clears_behavior_based_intro_and_credits_markers {
            get {
                return ResourceManager.GetString("ClearChapterMarkersTask_Description_Clears_behavior_based_intro_and_credits_marke" +
                        "rs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Episode Intros.
        /// </summary>
        public static string ClearChapterMarkersTask_Name_Clear_Episode_Intros {
            get {
                return ResourceManager.GetString("ClearChapterMarkersTask_Name_Clear_Episode_Intros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts intro fingerprint from episodes.
        /// </summary>
        public static string ExtractIntroFingerprintTask_Description_Extracts_intro_fingerprint_from_episodes {
            get {
                return ResourceManager.GetString("ExtractIntroFingerprintTask_Description_Extracts_intro_fingerprint_from_episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Intro Fingerprint.
        /// </summary>
        public static string ExtractIntroFingerprintTask_Name_Extract_Intro_Fingerprint {
            get {
                return ResourceManager.GetString("ExtractIntroFingerprintTask_Name_Extract_Intro_Fingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts media info from videos and audios.
        /// </summary>
        public static string ExtractMediaInfoTask_Description_Extracts_media_info_from_videos_and_audios {
            get {
                return ResourceManager.GetString("ExtractMediaInfoTask_Description_Extracts_media_info_from_videos_and_audios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract MediaInfo.
        /// </summary>
        public static string ExtractMediaInfoTask_Name_Extract_MediaInfo {
            get {
                return ResourceManager.GetString("ExtractMediaInfoTask_Name_Extract_MediaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❤️Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralOptions_EditorTitle_General_Options {
            get {
                return ResourceManager.GetString("GeneralOptions_EditorTitle_General_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto merge multiple versions stored in the same folder. Default is OFF..
        /// </summary>
        public static string GeneralOptions_MergeMultiVersion_Auto_merge_multiple_versions_if_in_the_same_folder_ {
            get {
                return ResourceManager.GetString("GeneralOptions_MergeMultiVersion_Auto_merge_multiple_versions_if_in_the_same_fold" +
                        "er_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Merge Multi-version.
        /// </summary>
        public static string GeneralOptions_MergeMultiVersion_Merge_Multiple_Versions {
            get {
                return ResourceManager.GetString("GeneralOptions_MergeMultiVersion_Merge_Multiple_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro Detection Fingerprint Length (Minute), Default is 10.
        /// </summary>
        public static string IntroSkipOptions_IntroDetectionFingerprintMinutes_Intro_Detection_Fingerprint_Minutes {
            get {
                return ResourceManager.GetString("IntroSkipOptions_IntroDetectionFingerprintMinutes_Intro_Detection_Fingerprint_Min" +
                        "utes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Scope.
        /// </summary>
        public static string IntroSkipOptions_LibraryScope_Library_Scope {
            get {
                return ResourceManager.GetString("IntroSkipOptions_LibraryScope_Library_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV shows library scope to detect. Blank includes all TV shows libraries..
        /// </summary>
        public static string IntroSkipOptions_LibraryScope_TV_shows_library_scope_to_detect__Blank_includes_all_ {
            get {
                return ResourceManager.GetString("IntroSkipOptions_LibraryScope_TV_shows_library_scope_to_detect__Blank_includes_al" +
                        "l_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library scope to extract fingerprint. Blank includes all libraries with intro detection enabled..
        /// </summary>
        public static string IntroSkipOptions_MarkerEnabledLibraryScope_Intro_detection_enabled_library_scope__Blank_includes_all_ {
            get {
                return ResourceManager.GetString("IntroSkipOptions_MarkerEnabledLibraryScope_Intro_detection_enabled_library_scope_" +
                        "_Blank_includes_all_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Scope.
        /// </summary>
        public static string IntroSkipOptions_MarkerEnabledLibraryScope_Library_Scope {
            get {
                return ResourceManager.GetString("IntroSkipOptions_MarkerEnabledLibraryScope_Library_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Credits Duration (Seconds), Default is 360.
        /// </summary>
        public static string IntroSkipOptions_MaxCreditsDurationSeconds {
            get {
                return ResourceManager.GetString("IntroSkipOptions_MaxCreditsDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Intro Duration (Seconds), Default is 150.
        /// </summary>
        public static string IntroSkipOptions_MaxIntroDurationSeconds {
            get {
                return ResourceManager.GetString("IntroSkipOptions_MaxIntroDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Opening Plot Duration (Seconds), Default is 60.
        /// </summary>
        public static string IntroSkipOptions_MinOpeningPlotDurationSeconds {
            get {
                return ResourceManager.GetString("IntroSkipOptions_MinOpeningPlotDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in Intro Detection Enhanced.
        /// </summary>
        public static string IntroSkipOptions_UnlockIntroSkip_Built_in_Intro_Skip_Enhanced {
            get {
                return ResourceManager.GetString("IntroSkipOptions_UnlockIntroSkip_Built_in_Intro_Skip_Enhanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize intro detection fingerprint length, unlock Strm support. Default is OFF..
        /// </summary>
        public static string IntroSkipOptions_UnlockIntroSkip_Unlock_Strm_support_for_built_in_intro_skip_detection {
            get {
                return ResourceManager.GetString("IntroSkipOptions_UnlockIntroSkip_Unlock_Strm_support_for_built_in_intro_skip_dete" +
                        "ction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Users.
        /// </summary>
        public static string IntroSkipOptions_UserScope_User_Scope {
            get {
                return ResourceManager.GetString("IntroSkipOptions_UserScope_User_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users allowed to detect. Blank includes all users..
        /// </summary>
        public static string IntroSkipOptions_UserScope_Users_allowed_to_detect__Blank_includes_all {
            get {
                return ResourceManager.GetString("IntroSkipOptions_UserScope_Users_allowed_to_detect__Blank_includes_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative MovieDb Api Key is invalid.
        /// </summary>
        public static string InvalidAltMovieDbApiKey {
            get {
                return ResourceManager.GetString("InvalidAltMovieDbApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative MovieDb Api Url is invalid.
        /// </summary>
        public static string InvalidAltMovieDbApiUrl {
            get {
                return ResourceManager.GetString("InvalidAltMovieDbApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative MovieDb Image Url is invalid.
        /// </summary>
        public static string InvalidAltMovieDbImageUrl {
            get {
                return ResourceManager.GetString("InvalidAltMovieDbImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string ItemType_Book_Book {
            get {
                return ResourceManager.GetString("ItemType_Book_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string ItemType_Collection_Collection {
            get {
                return ResourceManager.GetString("ItemType_Collection_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode.
        /// </summary>
        public static string ItemType_Episode_Episode {
            get {
                return ResourceManager.GetString("ItemType_Episode_Episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string ItemType_Game_Game {
            get {
                return ResourceManager.GetString("ItemType_Game_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string ItemType_Genre_Genre {
            get {
                return ResourceManager.GetString("ItemType_Genre_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveTv.
        /// </summary>
        public static string ItemType_LiveTv_LiveTv {
            get {
                return ResourceManager.GetString("ItemType_LiveTv_LiveTv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        public static string ItemType_Movie_Movie {
            get {
                return ResourceManager.GetString("ItemType_Movie_Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string ItemType_Music_Music {
            get {
                return ResourceManager.GetString("ItemType_Music_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Album.
        /// </summary>
        public static string ItemType_MusicAlbum_MusicAlbum {
            get {
                return ResourceManager.GetString("ItemType_MusicAlbum_MusicAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Artist.
        /// </summary>
        public static string ItemType_MusicArtist_MusicArtist {
            get {
                return ResourceManager.GetString("ItemType_MusicArtist_MusicArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string ItemType_Person_Person {
            get {
                return ResourceManager.GetString("ItemType_Person_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string ItemType_Photo_Photo {
            get {
                return ResourceManager.GetString("ItemType_Photo_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Album.
        /// </summary>
        public static string ItemType_PhotoAlbum_PhotoAlbum {
            get {
                return ResourceManager.GetString("ItemType_PhotoAlbum_PhotoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string ItemType_Playlist_Playlist {
            get {
                return ResourceManager.GetString("ItemType_Playlist_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string ItemType_Series_Series {
            get {
                return ResourceManager.GetString("ItemType_Series_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio.
        /// </summary>
        public static string ItemType_Studio_Studio {
            get {
                return ResourceManager.GetString("ItemType_Studio_Studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string ItemType_Tag_Tag {
            get {
                return ResourceManager.GetString("ItemType_Tag_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer.
        /// </summary>
        public static string ItemType_Trailer_Trailer {
            get {
                return ResourceManager.GetString("ItemType_Trailer_Trailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional MediaInfo JSON Root Folder.
        /// </summary>
        public static string MediaInfoExtractOptions_MediaInfoJsonRootFolder_MediaInfo_Json_Root_Folder {
            get {
                return ResourceManager.GetString("MediaInfoExtractOptions_MediaInfoJsonRootFolder_MediaInfo_Json_Root_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store or load media info JSON files under this root folder. Default is EMPTY..
        /// </summary>
        public static string MediaInfoExtractOptions_MediaInfoJsonRootFolder_Store_or_load_media_info_JSON_files_under_this_root_folder__Default_is_EMPTY_ {
            get {
                return ResourceManager.GetString("MediaInfoExtractOptions_MediaInfoJsonRootFolder_Store_or_load_media_info_JSON_fil" +
                        "es_under_this_root_folder__Default_is_EMPTY_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store or load media info and chapters to/from JSON file. Default is OFF..
        /// </summary>
        public static string MediaInfoExtractOptions_PersistMediaInfo_Persist_media_info_in_JSON_file__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("MediaInfoExtractOptions_PersistMediaInfo_Persist_media_info_in_JSON_file__Default" +
                        "_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaInfo Persist.
        /// </summary>
        public static string MediaInfoExtractOptions_PersistMediaInfo_Persist_MediaInfo {
            get {
                return ResourceManager.GetString("MediaInfoExtractOptions_PersistMediaInfo_Persist_MediaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative MovieDb Api Key.
        /// </summary>
        public static string MetadataEnhanceOptions_AltMovieDbApiKey_Alternative_MovieDb_Api_Key {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_AltMovieDbApiKey_Alternative_MovieDb_Api_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your own Api Key. Blank uses system default..
        /// </summary>
        public static string MetadataEnhanceOptions_AltMovieDbApiKey_Provide_your_own_MovieDb_Api_Key__Blank_uses_system_default_ {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_AltMovieDbApiKey_Provide_your_own_MovieDb_Api_Key__Blank_u" +
                        "ses_system_default_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative MovieDb Api Url.
        /// </summary>
        public static string MetadataEnhanceOptions_AltMovieDbApiUrl_Alternative_MovieDb_Api_Url {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_AltMovieDbApiUrl_Alternative_MovieDb_Api_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default alternative URL is https://api.tmdb.org Blank uses system default https://api.themoviedb.org.
        /// </summary>
        public static string MetadataEnhanceOptions_AltMovieDbApiUrl_Default_alternative_is_https___api_tmdb_org {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_AltMovieDbApiUrl_Default_alternative_is_https___api_tmdb_o" +
                        "rg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative MovieDb Image Url.
        /// </summary>
        public static string MetadataEnhanceOptions_AltMovieDbImageUrl_Alternative_MovieDb_Image_Url {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_AltMovieDbImageUrl_Alternative_MovieDb_Image_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your own alternative Url. Blank uses system default https://image.tmdb.org.
        /// </summary>
        public static string MetadataEnhanceOptions_AltMovieDbImageUrl_No_default_alternative__Provide_by_yourself_ {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_AltMovieDbImageUrl_No_default_alternative__Provide_by_your" +
                        "self_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Alternative MovieDb Config.
        /// </summary>
        public static string MetadataEnhanceOptions_EnableAltMovieDbUrl {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_EnableAltMovieDbUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance MovieDb Person.
        /// </summary>
        public static string MetadataEnhanceOptions_EnhanceMovieDbPerson_Enhance_MovieDb_Person {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_EnhanceMovieDbPerson_Enhance_MovieDb_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract also_known_as when refresh person, import season cast, update series cast. Default is OFF..
        /// </summary>
        public static string MetadataEnhanceOptions_EnhanceMovieDbPerson_Import_season_cast_and_update_series_people__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_EnhanceMovieDbPerson_Import_season_cast_and_update_series_" +
                        "people__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add support to import actor image URL from Nfo. Default is OFF..
        /// </summary>
        public static string MetadataEnhanceOptions_EnhanceNfoMetadata_Add_support_to_import_actor_image_url__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_EnhanceNfoMetadata_Add_support_to_import_actor_image_url__" +
                        "Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nfo Metadata Import Enhanced.
        /// </summary>
        public static string MetadataEnhanceOptions_EnhanceNfoMetadata_Nfo_Metadata_Import_Enhanced {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_EnhanceNfoMetadata_Nfo_Metadata_Import_Enhanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize MovieDb Fallback Language.
        /// </summary>
        public static string ModOptions_ChineseMovieDb_Chinese_MovieDb {
            get {
                return ResourceManager.GetString("ModOptions_ChineseMovieDb_Chinese_MovieDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to get Chinese or Japanese metadata from MovieDb. Default is OFF..
        /// </summary>
        public static string ModOptions_ChineseMovieDb_Optimize_MovieDb_for_Chinese_metadata__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_ChineseMovieDb_Optimize_MovieDb_for_Chinese_metadata__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Search Enhanced.
        /// </summary>
        public static string ModOptions_EnhanceChineseSearch_Enhance_Chinese_Search {
            get {
                return ResourceManager.GetString("ModOptions_EnhanceChineseSearch_Enhance_Chinese_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Chinese fuzzy search and Pinyin search. Default is OFF..
        /// </summary>
        public static string ModOptions_EnhanceChineseSearch_Support_Chinese_fuzzy_search_and_Pinyin_search__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_EnhanceChineseSearch_Support_Chinese_fuzzy_search_and_Pinyin_search__D" +
                        "efault_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive MediaInfo Extract.
        /// </summary>
        public static string ModOptions_ExclusiveExtract_Exclusive_Extract {
            get {
                return ResourceManager.GetString("ModOptions_ExclusiveExtract_Exclusive_Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only allow this plugin to extract media info (ffprobe) and capture image (ffmpeg) for all libraries. Default is OFF..
        /// </summary>
        public static string ModOptions_ExclusiveExtract_Only_allow_this_plugin_to_extract_media_info__ffprobe__and_capture_image__ffmpeg___Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_ExclusiveExtract_Only_allow_this_plugin_to_extract_media_info__ffprobe" +
                        "__and_capture_image__ffmpeg___Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback Languages.
        /// </summary>
        public static string ModOptions_FallbackLanguages_Fallback_Languages {
            get {
                return ResourceManager.GetString("ModOptions_FallbackLanguages_Fallback_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback metadata languages..
        /// </summary>
        public static string ModOptions_FallbackLanguages_Fallback_languages__Default_is_zh_SG_ {
            get {
                return ResourceManager.GetString("ModOptions_FallbackLanguages_Fallback_languages__Default_is_zh_SG_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Person without Image.
        /// </summary>
        public static string ModOptions_HidePersonNoImage_Hide_Person_without_Image {
            get {
                return ResourceManager.GetString("ModOptions_HidePersonNoImage_Hide_Person_without_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide person without image. Default is OFF..
        /// </summary>
        public static string ModOptions_HidePersonNoImage_Hide_person_without_image__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_HidePersonNoImage_Hide_person_without_image__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Language Poster.
        /// </summary>
        public static string ModOptions_OriginalPoster_Original_Poster {
            get {
                return ResourceManager.GetString("ModOptions_OriginalPoster_Original_Poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer original poster based on the original language. Support TMDB, TVDB and FANART. Default is OFF..
        /// </summary>
        public static string ModOptions_OriginalPoster_Show_original_poster_based_on_original_language__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_OriginalPoster_Show_original_poster_based_on_original_language__Defaul" +
                        "t_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto generate pinyin initials as sort title when library scan. Default is OFF..
        /// </summary>
        public static string ModOptions_PinyinSortName_Auto_generate_pinyin_initials_as_sort_title {
            get {
                return ResourceManager.GetString("ModOptions_PinyinSortName_Auto_generate_pinyin_initials_as_sort_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinyin Initials Sort Title.
        /// </summary>
        public static string ModOptions_PinyinSortName_Pinyin_Sort_Title {
            get {
                return ResourceManager.GetString("ModOptions_PinyinSortName_Pinyin_Sort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include search item types. Default is Movie, Collection, Series. Blank includes all..
        /// </summary>
        public static string ModOptions_SearchScope_Include_item_types__Blank_includes_all_ {
            get {
                return ResourceManager.GetString("ModOptions_SearchScope_Include_item_types__Blank_includes_all_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Scope.
        /// </summary>
        public static string ModOptions_SearchScope_Search_Scope {
            get {
                return ResourceManager.GetString("ModOptions_SearchScope_Search_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string No_Update_Message {
            get {
                return ResourceManager.GetString("No_Update_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch-up mode update - {0}\n\n{1}&apos;s favorite.
        /// </summary>
        public static string Notification_CatchupUpdate_EventDescription {
            get {
                return ResourceManager.GetString("Notification_CatchupUpdate_EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites Updated.
        /// </summary>
        public static string Notification_CatchupUpdate_EventName {
            get {
                return ResourceManager.GetString("Notification_CatchupUpdate_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} - Credits marker updated\n\nCredits duration: {2}\n\nby {3}.
        /// </summary>
        public static string Notification_CreditsUpdate_Description {
            get {
                return ResourceManager.GetString("Notification_CreditsUpdate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} - Credits marker updated.
        /// </summary>
        public static string Notification_CreditsUpdate_Message {
            get {
                return ResourceManager.GetString("Notification_CreditsUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntroSkip Updated.
        /// </summary>
        public static string Notification_IntroSkipUpdate_EventName {
            get {
                return ResourceManager.GetString("Notification_IntroSkipUpdate_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} - Intro marker updated\n\nIntro start time: {2}\nIntro end time: {3}\n\nby {4}.
        /// </summary>
        public static string Notification_IntroUpdate_Description {
            get {
                return ResourceManager.GetString("Notification_IntroUpdate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} - Intro marker updated.
        /// </summary>
        public static string Notification_IntroUpdate_Message {
            get {
                return ResourceManager.GetString("Notification_IntroUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persists media info to json file.
        /// </summary>
        public static string PersistMediaInfoTask_Description_Persists_media_info_to_json_file {
            get {
                return ResourceManager.GetString("PersistMediaInfoTask_Description_Persists_media_info_to_json_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist MediaInfo.
        /// </summary>
        public static string PersistMediaInfoTask_Name_Persist_MediaInfo {
            get {
                return ResourceManager.GetString("PersistMediaInfoTask_Name_Persist_MediaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch-up Mode.
        /// </summary>
        public static string PluginOptions_CatchupMode_Catch_up_Mode__Experimental_ {
            get {
                return ResourceManager.GetString("PluginOptions_CatchupMode_Catch_up_Mode__Experimental_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract media info for newly added items and sync intro and credits markers. Default is OFF..
        /// </summary>
        public static string PluginOptions_CatchupMode_Catch_up_users_favorites__exclusive_to_Strm___Default_is_False_ {
            get {
                return ResourceManager.GetString("PluginOptions_CatchupMode_Catch_up_users_favorites__exclusive_to_Strm___Default_i" +
                        "s_False_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strm Assistant.
        /// </summary>
        public static string PluginOptions_EditorTitle_Strm_Assistant {
            get {
                return ResourceManager.GetString("PluginOptions_EditorTitle_Strm_Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaInfo Extract.
        /// </summary>
        public static string PluginOptions_EditorTitle_Strm_Extract {
            get {
                return ResourceManager.GetString("PluginOptions_EditorTitle_Strm_Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Capture and Thumbnail Preview Enhanced.
        /// </summary>
        public static string PluginOptions_EnableImageCapture_Enable_Image_Capture {
            get {
                return ResourceManager.GetString("PluginOptions_EnableImageCapture_Enable_Image_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock image capture, thumbnail preview BIF for Strm. Skip embedded image. Default is OFF..
        /// </summary>
        public static string PluginOptions_EnableImageCapture_Perform_image_capture_for_videos_without_primary_image__Default_is_False_ {
            get {
                return ResourceManager.GetString("PluginOptions_EnableImageCapture_Perform_image_capture_for_videos_without_primary" +
                        "_image__Default_is_False_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptive Intro Skip.
        /// </summary>
        public static string PluginOptions_EnableIntroSkip_Enable_Intro_Skip__Experimental_ {
            get {
                return ResourceManager.GetString("PluginOptions_EnableIntroSkip_Enable_Intro_Skip__Experimental_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback behavior-based intro and credits detection for episodes. Default is OFF..
        /// </summary>
        public static string PluginOptions_EnableIntroSkip_Enable_intro_skip_and_credits_skip_for_episodes__Default_is_False_ {
            get {
                return ResourceManager.GetString("PluginOptions_EnableIntroSkip_Enable_intro_skip_and_credits_skip_for_episodes__De" +
                        "fault_is_False_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Additional Part and Extra.
        /// </summary>
        public static string PluginOptions_IncludeExtra_Include_Extra {
            get {
                return ResourceManager.GetString("PluginOptions_IncludeExtra_Include_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include additional parts and extras to extract. Default is OFF..
        /// </summary>
        public static string PluginOptions_IncludeExtra_Include_media_extras_to_extract__Default_is_False_ {
            get {
                return ResourceManager.GetString("PluginOptions_IncludeExtra_Include_media_extras_to_extract__Default_is_False_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please uninstall the conflict plugin StrmExtract.dll and then restart Emby..
        /// </summary>
        public static string PluginOptions_IncompatibleMessage_Please_uninstall_the_conflict_plugin_Strm_Extract {
            get {
                return ResourceManager.GetString("PluginOptions_IncompatibleMessage_Please_uninstall_the_conflict_plugin_Strm_Extra" +
                        "ct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro and Credits Detection.
        /// </summary>
        public static string PluginOptions_IntroSkipOptions_Intro_Credits_Detection {
            get {
                return ResourceManager.GetString("PluginOptions_IntroSkipOptions_Intro_Credits_Detection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Scope.
        /// </summary>
        public static string PluginOptions_LibraryScope_Library_Scope {
            get {
                return ResourceManager.GetString("PluginOptions_LibraryScope_Library_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library scope to extract. Blank includes all..
        /// </summary>
        public static string PluginOptions_LibraryScope_Library_scope_to_extract__Blank_includes_all_ {
            get {
                return ResourceManager.GetString("PluginOptions_LibraryScope_Library_scope_to_extract__Blank_includes_all_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Concurrent Count.
        /// </summary>
        public static string PluginOptions_MaxConcurrentCount_Max_Concurrent_Count {
            get {
                return ResourceManager.GetString("PluginOptions_MaxConcurrentCount_Max_Concurrent_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max concurrent count of threads to extract media info. It must be between 1 to 10. Default is 1..
        /// </summary>
        public static string PluginOptions_MaxConcurrentCount_Max_Concurrent_Count_must_be_between_1_to_10__Default_is_1_ {
            get {
                return ResourceManager.GetString("PluginOptions_MaxConcurrentCount_Max_Concurrent_Count_must_be_between_1_to_10__De" +
                        "fault_is_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Enhance.
        /// </summary>
        public static string PluginOptions_MetadataEnhanceOptions_Metadata_Enhance {
            get {
                return ResourceManager.GetString("PluginOptions_MetadataEnhanceOptions_Metadata_Enhance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod.
        /// </summary>
        public static string PluginOptions_ModOptions_Mod_Features {
            get {
                return ResourceManager.GetString("PluginOptions_ModOptions_Mod_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Strm only. Turn off to support all. Default is ON..
        /// </summary>
        public static string PluginOptions_StrmOnly_Extract_media_info_of_Strm_only__Default_is_True_ {
            get {
                return ResourceManager.GetString("PluginOptions_StrmOnly_Extract_media_info_of_Strm_only__Default_is_True_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strm Only.
        /// </summary>
        public static string PluginOptions_StrmOnly_Strm_Only {
            get {
                return ResourceManager.GetString("PluginOptions_StrmOnly_Strm_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshes and repairs Chinese actors.
        /// </summary>
        public static string RefreshPersonTask_Description_Refreshes_and_repairs_Chinese_actors {
            get {
                return ResourceManager.GetString("RefreshPersonTask_Description_Refreshes_and_repairs_Chinese_actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Chinese Actor.
        /// </summary>
        public static string RefreshPersonTask_Name_Refresh_Chinese_Actor {
            get {
                return ResourceManager.GetString("RefreshPersonTask_Name_Refresh_Chinese_Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repo Link.
        /// </summary>
        public static string Repo_Link {
            get {
                return ResourceManager.GetString("Repo_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans external subtitles for videos.
        /// </summary>
        public static string ScanExternalSubtitleTask_Description_Scans_external_subtitles_for_videos {
            get {
                return ResourceManager.GetString("ScanExternalSubtitleTask_Description_Scans_external_subtitles_for_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan External Subtitles.
        /// </summary>
        public static string ScanExternalSubtitleTask_Name_Scan_External_Subtitles {
            get {
                return ResourceManager.GetString("ScanExternalSubtitleTask_Name_Scan_External_Subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beautify Episode Title.
        /// </summary>
        public static string UIFunctionOptions_BeautifyMissingMetadata_Beautify_Missing_Metadata {
            get {
                return ResourceManager.GetString("UIFunctionOptions_BeautifyMissingMetadata_Beautify_Missing_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beautify episode title display with no metadata. Default is OFF..
        /// </summary>
        public static string UIFunctionOptions_BeautifyMissingMetadata_Beautify_missing_metadata_for_episode_display__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("UIFunctionOptions_BeautifyMissingMetadata_Beautify_missing_metadata_for_episode_d" +
                        "isplay__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Functions.
        /// </summary>
        public static string UIFunctionOptions_EditorTitle_UI_Functions {
            get {
                return ResourceManager.GetString("UIFunctionOptions_EditorTitle_UI_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforce Library Order.
        /// </summary>
        public static string UIFunctionOptions_EnforceLibraryOrder_Enforce_Library_Order {
            get {
                return ResourceManager.GetString("UIFunctionOptions_EnforceLibraryOrder_Enforce_Library_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforce customized library order per the first admin. Default if OFF..
        /// </summary>
        public static string UIFunctionOptions_EnforceLibraryOrder_Enforce_library_order_per_the_first_admin__Default_if_OFF_ {
            get {
                return ResourceManager.GetString("UIFunctionOptions_EnforceLibraryOrder_Enforce_library_order_per_the_first_admin__" +
                        "Default_if_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add MovieDb support for the view missing episodes function. Default is OFF..
        /// </summary>
        public static string UIFunctionOptions_EnhanceMissingEpisodes_Add_MovieDb_support_for_the_missing_episodes_function__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("UIFunctionOptions_EnhanceMissingEpisodes_Add_MovieDb_support_for_the_missing_epis" +
                        "odes_function__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Missing Episodes Enhanced.
        /// </summary>
        public static string UIFunctionOptions_EnhanceMissingEpisodes_Missing_Episodes_Enhanced {
            get {
                return ResourceManager.GetString("UIFunctionOptions_EnhanceMissingEpisodes_Missing_Episodes_Enhanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Emby won&apos;t work without turning off Chinese Search Enhanced properly..
        /// </summary>
        public static string Uninstall_Warning {
            get {
                return ResourceManager.GetString("Uninstall_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates plugin to the latest version.
        /// </summary>
        public static string UpdatePluginTask_Description_Updates_plugin_to_the_latest_version {
            get {
                return ResourceManager.GetString("UpdatePluginTask_Description_Updates_plugin_to_the_latest_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Plugin.
        /// </summary>
        public static string UpdatePluginTask_Name_Update_Plugin {
            get {
                return ResourceManager.GetString("UpdatePluginTask_Name_Update_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Link.
        /// </summary>
        public static string Wiki_Link {
            get {
                return ResourceManager.GetString("Wiki_Link", resourceCulture);
            }
        }
    }
}
