name: Build Plugin

on:
  push:
    branches:
      - tab-ui
      - simple-ui
      - lite
  pull_request:
    branches:
      - tab-ui
      - simple-ui
      - lite

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore --configuration Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: StrmAssistant
          path: C:\Users\runneradmin\AppData\Roaming\Emby-Server\programdata\plugins\StrmAssistant.dll
